import type { Metadata } from 'next'
import './globals.css'
// import localFont from 'next/font/local'

// const clashDisplay = localFont({
//   src: "fonts/ClashDisplay-Regular.woff2",
//   variable: '--font-clashdisplay'
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        {children}
      </body>
    </html>
  )
}
