import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

const clashDisplay = localFont({
  src: 'public/fonts/fonts/ClashDisplay-Regular.ttf',
  variable: '--font-clashdisplay'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} font-sans`}>
        {children}
      </body>
    </html>
  )
}
